---
abstract: 'Extract text from QuickMemo+ LQM export files.'
author:
  - 'Brent Shields <bshields@cpan.org>'
build_requires:
  Test::More: '0.98'
  Test::Warn: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.028, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-QuickMemoPlus-Reader
provides:
  Data::QuickMemoPlus::Reader:
    file: lib/Data/QuickMemoPlus/Reader.pm
    version: '0.10'
requires:
  Archive::Zip: '0'
  Carp: '0'
  JSON: '0'
  perl: '5.008001'
version: '0.10'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
